before_install:
  - if [ "$TRAVIS_ARCH" = "ppc64le" ]; then sudo apt-get update; sudo apt-get install erlang;sudo apt-get install rebar; fi
  - pip install --user cpp-coveralls coveralls-merge
language: erlang

os: linux
arch:
  - amd64
  - ppc64le

dist: xenial

install:
  - rebar get-deps

script: rebar compile xref && rebar skip_deps=true eunit

otp_release:
  - 19.3
  - 22.3
  - 23.0

after_success:
  - cpp-coveralls --exclude lib --exclude tests --gcov-options '\-lp' --dump c.json
  - coveralls-merge c.json erlang.json
